/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffdbce',
        'surface-container': '#ebefed',
        'bg-canvas': '#F8FAF9',
        'on-primary': '#ffffff',
        'secondary-fixed': '#ffddb8',
        'on-primary-fixed': '#00201d',
        'on-surface-variant': '#3e4947',
        'on-error-container': '#93000a',
        'danger-crimson': '#DC2626',
        'inverse-primary': '#80d5cb',
        'on-background': '#181c1c',
        'surface-container-low': '#f1f4f3',
        'on-tertiary-fixed-variant': '#72361b',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'surface-container-high': '#e5e9e7',
        'primary-container': '#0f766e',
        'surface-dim': '#d7dbd9',
        'surface-bright': '#f7faf8',
        'outline': '#6e7977',
        'secondary': '#855300',
        'primary': '#005c55',
        'inverse-on-surface': '#eef1f0',
        'on-tertiary-container': '#ffe5db',
        'surface-variant': '#e0e3e1',
        'background': '#f7faf8',
        'tertiary': '#7f4025',
        'on-surface': '#181c1c',
        'secondary-fixed-dim': '#ffb95f',
        'outline-variant': '#bdc9c6',
        'on-tertiary-fixed': '#370e00',
        'on-error': '#ffffff',
        'inverse-surface': '#2d3130',
        'on-primary-fixed-variant': '#00504a',
        'tertiary-container': '#9c573a',
        'error-container': '#ffdad6',
        'on-primary-container': '#a3faef',
        'on-secondary-container': '#684000',
        'secondary-container': '#fea619',
        'success-clinical': '#22C55E',
        'surface-container-highest': '#e0e3e1',
        'tertiary-fixed-dim': '#ffb598',
        'on-secondary': '#ffffff',
        'surface': '#f7faf8',
        'on-secondary-fixed': '#2a1700',
        'surface-subtle': '#F1F5F4',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#006a63',
        'primary-fixed-dim': '#80d5cb',
        'on-secondary-fixed-variant': '#653e00',
        'primary-fixed': '#9cf2e8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '2rem',
        'container-max': '820px',
        'stack-md': '1rem',
        'stack-sm': '0.5rem',
        'margin-mobile': '1rem',
        'gutter': '1.5rem',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'mono': ['IBM Plex Mono', 'monospace'],
        'code-md': ['IBM Plex Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
